Document: prettyripper
Title: Debian prettyripper Manual
Author: <insert document author here>
Abstract: This manual describes what prettyripper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/prettyripper/prettyripper.sgml.gz

Format: postscript
Files: /usr/share/doc/prettyripper/prettyripper.ps.gz

Format: text
Files: /usr/share/doc/prettyripper/prettyripper.text.gz

Format: HTML
Index: /usr/share/doc/prettyripper/html/index.html
Files: /usr/share/doc/prettyripper/html/*.html
